name: test-env-vars

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
env: 
  env_var: ${{ vars.ENV_CONTECT_VAR }}
jobs:
  print_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        run: |
          echo "${{ env.env_var }}"
