name: test-env-vars

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
env: 
  some_key: ${{ vars.SOME_KEY }}
jobs:
  print_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        run: |
          echo "${{ env.some_key }}"
